version: '3.8'
services:
  mysql:
      container_name: mysql8
      image: bitnami/mysql:8.0
      # command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: symfony_docker
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - '3306:3306'
      volumes:
        - ./.docker/mysql:/bitnami/mysql/data

  phpadmin:
    container_name: php_admin5
    image: bitnami/phpmyadmin:5.2.1
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  php:
    container_name: php8-apache
    build:
      context: ./.docker
    ports:
      - '80:80'
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - phpadmin