version: '3.8'

services:
  mysql:
    container_name: mysql8
    image: bitnami/mysql:8.0
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: no
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/mysql:/bitnami/mysql/data

  phpadmin:
    container_name: php_admin5
    image: bitnami/phpmyadmin:5.2.1
    environment:
      DATABASE_ALLOW_NO_PASSWORD: no
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - mysql
  php:
    container_name: app
    build:
      context: ./.docker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/docker.local
    depends_on:
      - mysql
      - phpadmin
